FROM python:3.12

# 安装依赖
COPY   ./requirements.txt /appserver/
RUN pip install --no-cache-dir   -Ur /appserver/requirements.txt  -i https://mirrors.cloud.tencent.com/pypi/simple

# FROM ACCOUNT_BASE
# 设置检查
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "curl  ${host}:${port}/health" ]

# 安装依赖
COPY   ./requirements.txt /appserver/
COPY ./src/   /appserver/src/
WORKDIR /appserver
CMD ["python", "./src/main.py"]

