# syntax=docker/dockerfile:1
FROM python:3.12

# 安装依赖
COPY   ./requirements.txt /appserver/
RUN pip install --no-cache-dir   -Ur /appserver/requirements.txt  -i https://mirrors.cloud.tencent.com/pypi/simple


