name: "测试环境自动更新"
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }} @ ${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  update_supervisor_server:
    runs-on: macOS
    timeout-minutes: 5

    steps:
      - name: 更新代码
        run: |
          cd ~/Desktop/myselfproject/supervisor_services/services/account-server/
          git checkout ${GITHUB_REF#refs/heads/}
          git pull

      - name: 更新环境
        run: |
          export PYENV_ROOT="$HOME/anyenv/envs/pyenv"
          command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"

          cd ~/Desktop/myselfproject/supervisor_services/services/account-server/
          pyenv virtualenv 3.12.2 account-server || true
          pyenv activate account-server || true
          python -m pip install -Ur ./requirements.txt -i https://mirrors.cloud.tencent.com/pypi/simple

      - name: 测试
        env:
          ACCOUNT_SERVER_MYSQL_DSN: ${{ secrets.MAC_RUNNER_MYSQL_DSN }}
        run: |
          export PYENV_ROOT="$HOME/anyenv/envs/pyenv"
          command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          cd ~/Desktop/myselfproject/supervisor_services/services/account-server/
          pyenv activate account-server
          source .env
          python -m pytest ./tests

      - name: 重启服务
        run: |
          cd ~/Desktop/myselfproject/supervisor_services/
          ./supervisorctl.sh status  "account:*" 
          ./supervisorctl.sh  restart "account:*"
          ./supervisorctl.sh status  "account:*"
