name: "测试"
on:
  workflow_dispatch:
  push:
    branches:
      - prepare
      - dev
permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }} @ ${{github.event.pull_request.head.label || github.head_ref || github.ref}}"
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ["ubuntu-latest"]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    env:
      account_server_mysql_dsn: "mysql+pymysql://root:daskjfelwjre234klfe@127.0.0.1:3306/tts"

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_USER: testtts
          MYSQL_PASSWORD: daskjfelwjre234klfe
          # MYSQL_DATABASE: test_tts
          MYSQL_ROOT_PASSWORD: daskjfelwjre234klfe
          MYSQL_ROOT_HOST: 0.0.0.0
          options: --name=mariadbtest --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        volumes:
        - docker-entrypoint-initdb.d:/tmp/sql

    steps:

      - name: checkout
        uses: actions/checkout@v4
      - name: init db table by sql
        run: |
          #docker exec ${{ job.services.mariadb.id }} -it  bash mkdir -p /tmp/sql/
          #docker cp ./src/dbsql/init.sql ${{ job.services.mariadb.id }}:/tmp/
          sudo apt-get install mysql-client 
          #docker exec ${{ job.services.mariadb.id }} ls /tmp/
          #docker exec ${{ job.services.mariadb.id }} bash  -c 'mariadb -uroot -pdaskjfelwjre234klfe < /tmp/init.sql'
          mysql -h 127.0.0.1 -uroot  -pdaskjfelwjre234klfe <./src/dbsql/init.sql

      - name: install python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: install pytest
        run: pip install pytest

      - name: install requirement.txt
        run: |
          cat requirements.txt
          pip install -r requirements.txt

      - name: run test
        run: |
          cd src/
          pytest  tests/
