name: "测试"
on:
  workflow_dispatch:
  push:
    branches:
      - prepare
      - dev
permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }} @ ${{github.event.pull_request.head.label || github.head_ref || github.ref}}"
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ["ubuntu-latest"]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    env:
      account_server_mysql_dsn: ${{ secrets.ACCOUNT_SERVER_MYSQL_DSN}}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: install pytest
        run:  pip install pytest

      - name: install requirement.txt
        run: |
          cat requirement.txt
          pip install -r requirement.txt
      
      - name: run test
        run: |
          cd src/
          pytest  tests/